owner: iguinhus                                                                       
  repo: clima-creators-status                                                           
                                                                                        
  sites:                                                                                
    - name: Clima Creators (Dev)                                                        
      url: https://climacreators.vercel.app                                             
                                                                                        
    - name: Supabase                                                                    
      url: https://status.supabase.com                                                  
                                                                                        
    - name: Vercel                                                                      
      url: https://www.vercel-status.com                                                
                                                                                        
    - name: Sentry                                                                      
      url: https://status.sentry.io                                                     
                                                                                        
    - name: PostHog                                                                     
      url: https://status.posthog.com                                                   
                                                                                        
    - name: Resend                                                                      
      url: https://resend-status.com                                                    
                                                                                        
    - name: Pluggy                                                                      
      url: https://status.pluggy.ai                                                     
                                                                                        
  status-website:                                                                       
    baseUrl: /clima-creators-status                                                     
    name: Clima Creators                                                                
    introTitle: "Status dos Servicos"                                                   
    introMessage: "Monitoramento em tempo real da plataforma Clima Creators."           
    navbar:                                                                             
      - title: Status                                                                   
        href: /                                                                         
      - title: Clima Creators                                                           
        href: https://climacreators.vercel.app                                          
                                                                                        
  assignees:                                                                            
    - iguinhus                                                                          
                                                                                        
  workflowSchedule:                                                                     
    uptime: "*/5 * * * *"                                                               
    responseTime: "0 */6 * * *"                                                         
    staticSite: "0 1 * * *"                                                             
    summary: "0 0 * * *"                                                                
    graphs: "0 0 * * *"                                                                 
                                                                                        
  commitMessages:                                                                       
    commitAuthorName: Upptime Bot                                                       
    commitAuthorEmail: upptime@climacreators.com.br                                     
                                                                                        
  i18n:                                                                                 
    activeIncidents: Incidentes Ativos                                                  
    allSystemsOperational: Todos os sistemas operacionais                               
    incidentReport: Incidente $NUMBER                                                   
    activeIncidentSummary: Detectado ha $MINUTES minutos                                
    incidentTitle: Detalhes do Incidente                                                
    incidentDetails: Detalhes                                                           
    incidentFixed: Resolvido                                                            
    incidentOngoing: Em andamento                                                       
    incidentDegraded: Degradado                                                         
    incidentDown: Fora do ar                                                            
    pastIncidents: Incidentes Recentes                                                  
    pastIncidentsResolved: Incidentes resolvidos nos ultimos 7 dias                     
    liveStatus: Status Atual                                                            
    overallUptime: Disponibilidade nos ultimos $DAYS dias                               
    overallUptimeTitle: Disponibilidade Geral                                           
    averageResponseTime: Tempo medio de resposta                                        
    up: Operacional                                                                     
    down: Fora do ar                                                                    
    degraded: Degradado                                                                 
    ms: ms                                                                              
    loading: Carregando                                                                 
    responseTimeGraphs: Historico de Tempo de Resposta  
